[package]
name = "resource_monitor"
version = "0.1.1"
edition = "2024"

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = ["accesskit", "default_fonts", "wgpu"] }
semver = "1.0.28"
serde_json = "1.0.151"
sysinfo = "0.38.4"
ureq = { version = "3.4.0", features = ["json"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
