[package]
name = "resource_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = ["accesskit", "default_fonts", "wgpu"] }
sysinfo = "0.38.4"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
